version: "3.9"

services:
    web:
        image: "folio-venv:dev"
        build:
            target: development_build
            context: .
            args:
                DJANGO_ENV: development
        command: >
            sh -c "python manage.py wait_for_db &&
                    python manage.py runserver 0.0.0.0:8000"
        ports:
            - 8000:8000
        volumes:
            - ./folio_backend:/folio_backend
        env_file:
            - ./.env
        depends_on:
            - db
    db:
        image: postgres:13.0-alpine
        restart: unless-stopped
        env_file:
            - ./.env
        volumes:
            - postgres_data:/var/lib/postgresql/data/

volumes:
    postgres_data:
