name: Dev Worflow -  Only Test

on: [push]

jobs:
    health-checkup-job: #Check the healthy by running tests
        runs-on: ubuntu-latest
        strategy:
            max-parallel: 4
            matrix:
                python-version: [3.8]
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Install Dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install poetry
                  poetry install
            # - name: Run migrations
            #   run: |
            #       cd folio_backend && python manage.py makemigrations --noinput
            #       cd folio_backend && python manage.py migrate --noinput
            # - name: Run Tests
            #   run: |
            #       cd folio_backend && poetry run python manage.py test
            # - name: Check Syntax #We are just testing the syntax in names app; pycodestyle uses pep8 conventions of max line length of 79 characters while Django recommends 119 characters
            #   run: pycodestyle --statistics names

    deploy-job:
        runs-on: ubuntu-latest
        needs: [health-checkup-job]
        if: ${{ github.event_name == 'push' }}
        steps:
            - uses: actions/checkout@v2
            - uses: akhileshns/heroku-deploy@v3.12.12
              with:
                  heroku_api_key: ${{secrets.HEROKU_API_KEY}}
                  heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
                  heroku_email: ${{secrets.HEROKU_EMAIL}}
                  branch: staging
                  # usedocker: true
